# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Cheat

on:
    workflow_dispatch:
#    push:
#        branches: [ "master" ]

permissions: write-all

jobs:
  build:
    name: Build project
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build
      run: msbuild -p:Configuration="Release" -p:Platform="x64"
    
    - name: Release
      id: release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.run_id }}
    - name: Upload PE
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./x64/Release/Dexterion.exe
        asset_name: Dexterion v${{ github.run_id }}.exe
        asset_content_type: application/exe
        
