# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Cheat

on:
    workflow_dispatch:
#    push:
#        branches: [ "master" ]

permissions: write-all

jobs:
  build:
    name: Build project
    runs-on: windows-latest
    outputs:
      DEXTERION_VERSION: ${{ steps.DEXTERION_VERSION.outputs.DEXTERION_VERSION }}
    steps:
    - uses: actions/checkout@v4
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build
      run: msbuild -p:Configuration="Release" -p:Platform="x64"
    - name: Get Version
      id: DEXTERION_VERSION
      run: |
          DEXTERION_VERSION=$(powershell -c -ExecutionPolicy Bypass $RawText = Get-Content D:\Users\Sergio\source\repos\Dexterion\util\utilFunctions.hpp -Raw; $Records = $RawText -split '(?=inline const wchar_t\* version = )'; $Records = $Records[1] -split '= L"'; $Records = $Records[1] -split '";'; $Records = $Records[0]; $Records);
          echo "DEXTERION_VERSION=$DEXTERION_VERSION" >> $GITHUB_ENV
    - name: Rename Dexterion
      run: |
          rename "./x64/Release/Dexterion.exe" "./x64/Release/Dexterion-${{ env.DEXTERION_VERSION }}.exe"
    - name: Release
      id: release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Upload PE
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./x64/Release/Dexterion.exe
        asset_name: Dexterion v2.1.0.exe
        asset_content_type: application/exe
        
