name: Build Cheat

on:
    workflow_dispatch:
#    push:
#        branches: [ "master" ]

permissions: write-all

jobs:
  build:
    name: Build project
    runs-on: windows-latest
    outputs:
      DEXTERION_VERSION: ${{ steps.DEXTERION_VERSION.outputs.DEXTERION_VERSION }}
    steps:
    - uses: actions/checkout@v4
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build
      run: msbuild -p:Configuration="Release" -p:Platform="x64"
    - name: Get Version
      id: DEXTERION_VERSION
      shell: pwsh
      run: |
          Set-ExecutionPolicy Bypass -Force
          $RawText = Get-Content ./util/utilFunctions.hpp -Raw
          $Records = $RawText -split '(?=inline std::string version = )'
          $Records = $Records[1] -split '= "'
          $Records = $Records[1] -split '";'
          $Records = $Records[0]
          Set-Variable DEXTERION_VERSION $Records
          #DEXTERION_VERSION=$(grep -Po 'version\s*=\s*"\K[^"]*' ./util/utilFunctions.hpp)
          echo "DEXTERION_VERSION=$DEXTERION_VERSION" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Zip Dexterion
      run: |
          curl -L "https://github.com/ip7z/7zip/releases/download/24.08/7zr.exe" > 7z.exe
          del x64\Release\Dexterion.pdb
          .\7z.exe a -t* "Dexterion-${{ env.DEXTERION_VERSION }}.zip" "x64\Release"
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Dexterion ${{ env.DEXTERION_VERSION }}
        tag_name: ${{ env.DEXTERION_VERSION }}
        body: |
          Installation:
          There are 2 files attached here:
          One is Dexterion-${{ env.DEXTERION_VERSION }}.zip which contains the cheat.
            
          Second one is updateoffests.cmd which updates the offsets when executing. 
        draft: false
        prerelease: false
        files: |
          ./Dexterion-${{ env.DEXTERION_VERSION }}.zip
          ./updateoffsets.cmd
    #- name: Upload PE
    #  uses: actions/upload-release-asset@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    upload_url: ${{ steps.release.outputs.upload_url }}
    #    asset_path: ./x64/Release/Dexterion.exe
    #    asset_name: Dexterion {{ env.DEXTERION_VERSION }}.exe
    #    asset_content_type: application/exe