name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1.0.2
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/users/Skwrr/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug, enhancement
          label-operator: OR